### ISSUE TITLE
ValueError: Directory data/preprocessed-power/test does not exist

### ISSUE THREAD

**Issue by mertyildiran** [timediv/speechT#18]
I installed speechT with:

```
sudo apt install python3-pip portaudio19-dev ffmpeg
pip3 install git+https://github.com/timediv/speechT
```

Then I wanted to test it with the pre-trained model by following [this section](https://github.com/timediv/speechT#trained-weights).

On `speecht-cli evaluate --run-name best_run` I'm getting this error:

```
Determine input size from first sample
Traceback (most recent call last):
  File "/home/mertyildiran/.local/bin/speecht-cli", line 221, in <module>
    cli.run()
  File "/home/mertyildiran/.local/bin/speecht-cli", line 207, in run
    self.command_executor.run()
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/lazy/lazy.py", line 28, in __get__
    value = self.__func(inst)
  File "/home/mertyildiran/.local/bin/speecht-cli", line 200, in command_executor
    }[self.parsed.command](self.parsed)
  File "/home/mertyildiran/.local/bin/speecht-cli", line 169, in _get_evaluation_executor
    return speecht.evaluation.Evaluation(flags)
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/execution.py", line 33, in __init__
    self.input_size = self.determine_input_size()
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/execution.py", line 41, in determine_input_size
    return next(self.create_sample_generator(limit_count=1))[0].shape[1]
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/preprocessing.py", line 261, in load_samples
    raise ValueError('Directory {} does not exist'.format(load_directory))
ValueError: Directory data/preprocessed-power/test does not exist
```

I found that it's related to [this line](https://github.com/timediv/speechT/blob/master/speecht/preprocessing.py#L204) but I don't know how to fix this error. @timediv could you help me please?

Thank you so much with this great project :+1: :blush:

**Comment by mertyildiran** [comment]
I also tried to run `speecht-cli record --run-name best_run` with the hope of testing the model with my microphone but this time I got this error:

```
Traceback (most recent call last):
  File "/home/mertyildiran/.local/bin/speecht-cli", line 221, in <module>
    cli.run()
  File "/home/mertyildiran/.local/bin/speecht-cli", line 207, in run
    self.command_executor.run()
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/recording.py", line 44, in run
    model.restore(sess, self.flags.run_train_dir)
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/speech_model.py", line 260, in restore
    raise FileNotFoundError('No checkpoint for evaluation found')
FileNotFoundError: No checkpoint for evaluation found
```

I think it's unable to load the pre-trained model (*checkpoint*) but I don't know how to fix that too.

**Comment by mertyildiran** [comment]
Now it's working fine with `speecht-cli record --run-name best_run` command. I don't know what was wrong, probably it was an issue with my tensorflow installation. So I'm closing the issue.
