### ISSUE TITLE
Unexpected keyword argument 'kenlm_directory_path'

### ISSUE THREAD

**Issue by mertyildiran** [timediv/speechT#20]
I'm trying to follow [Using a language model](https://github.com/timediv/speechT#using-a-language-model) section.

I have only tensorflow's official GPU installation.

With `speecht-cli record --run-name best_run --language-model kenlm-english/` command, I'm getting this error:

```
Traceback (most recent call last):
  File "/home/mertyildiran/.local/bin/speecht-cli", line 221, in <module>
    cli.run()
  File "/home/mertyildiran/.local/bin/speecht-cli", line 207, in run
    self.command_executor.run()
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/recording.py", line 43, in run
    model = create_default_model(self.flags, self.flags.input_size, speech_input_loader)
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/speech_model.py", line 318, in create_default_model
    valid_word_count_weight=flags.valid_word_count_weight)
  File "/home/mertyildiran/.local/lib/python3.5/site-packages/speecht/speech_model.py", line 111, in add_decoding_ops
    top_paths=1)
TypeError: ctc_beam_search_decoder() got an unexpected keyword argument 'kenlm_directory_path'
```

Probably because you said; "you need **Tensorflow with KenLM integration**" in that section. But I also stuck in [tensorflow-with-kenlm](https://github.com/timediv/tensorflow-with-kenlm)'s guide and I don't know what the exact cause. So I'm opening this issue as a question @timediv thank you so much.

*I also opened https://github.com/timediv/tensorflow-with-kenlm/issues/4*

**Comment by mertyildiran** [comment]
With the resolution of https://github.com/timediv/tensorflow-with-kenlm/issues/4, this issue is solved. Thanks anyway. :blush:
